import type { Capabilities } from '../lib/api';

/**
 * 화면이 쓰는 표시용 기본값만 남긴다(데이터는 전부 백엔드에서 온다).
 * 런타임을 새로 등록할 때 고를 수 있는 key 와 이름, 그리고 그 기본 capabilities.
 */
export const DEFAULT_PROVIDER_NAMES: Record<string, string> = {
  CLAUDE_CODE: 'Claude Code',
  CODEX: 'Codex',
  COMMAND_CODE: 'Command Code',
  GEMINI: 'Gemini',
};

/** 런타임을 새로 등록할 때 미리 채워 두는 값(이후 화면에서 편집하고 백엔드에 저장한다). */
export const DEFAULT_CAPABILITIES: Record<string, Capabilities> = {
  CLAUDE_CODE: {
    models: ['opus', 'sonnet', 'fable'],
    modes: ['default', 'acceptEdits', 'plan', 'bypassPermissions'],
    notes: 'claude --help 에 나온 alias 기준',
    install: ['npm install -g @anthropic-ai/claude-code'],
    installRequire: 'npm',
    installPrerequisite: ['nvm install lts', 'nvm use lts'],
  },
  CODEX: {
    models: [],
    modes: [],
    notes: 'CLI 설치 후 --help 로 확인해 채운다',
    install: ['npm install -g @openai/codex'],
    installRequire: 'npm',
    installPrerequisite: ['nvm install lts', 'nvm use lts'],
  },
  COMMAND_CODE: {
    // `cmdc --list-models` 로 실제 확인한 목록(Command Code v1.73.2). 추측 금지 — CLI 가 준 값만 적는다.
    models: [
      'deepseek/deepseek-v4-pro',
      'deepseek/deepseek-v4-flash',
      'deepseek/deepseek-v4-flash-vision-exp',
      'deepseek/deepseek-v4-flash-fast',
      'deepseek/deepseek-v4.1-flash',
      'deepseek/deepseek-v4.1-flash-fast',
      'moonshotai/kimi-k3',
      'moonshotai/kimi-k2.7-code',
      'moonshotai/kimi-k2.7-code-highspeed',
      'moonshotai/kimi-k2.6',
      'moonshotai/kimi-k2.5',
      'z-ai/glm-5.3-flash',
      'z-ai/glm-5.3-flashx',
      'zai-org/glm-5.3',
      'zai-org/glm-5.2',
      'zai-org/glm-5.2-fast',
      'zai-org/glm-5.1',
      'zai-org/glm-5',
      'minimaxai/minimax-m3',
      'minimaxai/minimax-m2.7',
      'minimaxai/minimax-m2.5',
      'xiaomi/mimo-v2.6-pro',
      'xiaomi/mimo-v2.6-pro-ultraspeed',
      'xiaomi/mimo-v2.6-flash',
      'xiaomi/mimo-v2.5-pro',
      'xiaomi/mimo-v2.5',
      'qwen/qwen3.8-omni-flash',
      'qwen/qwen3.8-max-0902',
      'qwen/qwen3.8-max',
      'qwen/qwen3.8-27b',
      'qwen/qwen3.8-flash',
      'qwen/qwen3.7-max',
      'qwen/qwen3.7-plus',
      'qwen/qwen3.7-flash',
      'qwen/qwen3.6-max-preview',
      'qwen/qwen3.6-plus',
      'meituan/longcat-2.0',
      'stepfun/step-5-preview',
      'stepfun/step-3.7-flash',
      'stepfun/step-3.5-flash',
      'tencent/hy3-paid',
      'tencent/hy4-preview',
      'nvidia/nemotron-3-ultra-550b-a55b',
      'thinkingmachines/inkling',
      'thinkingmachines/inkling-small',
      'poolside/laguna-s-2.1-free',
      'inclusionai/ling-3.0-flash-sante:free',
      'inclusionai/ling-3.1-flash:free',
      'stealth/space-bunny-alpha',
      'stealth/pixel-canary',
      'claude-sonnet-5-5',
      'claude-sonnet-5',
      'claude-sonnet-4-6',
      'claude-fable-5-1',
      'claude-fable-5',
      'claude-opus-5-5',
      'claude-opus-5',
      'claude-opus-4-8',
      'claude-opus-4-7',
      'claude-haiku-4-5',
      'gpt-6-astra',
      'gpt-6.1-sol',
      'gpt-6-sol',
      'gpt-6-luna',
      'gpt-5.6-sol',
      'gpt-5.6-terra',
      'gpt-5.6-luna',
      'gpt-5.5',
      'gpt-5.4',
      'gpt-5.3-codex',
      'gpt-5.4-mini',
      'google/gemini-3.8-flash',
      'google/gemini-3.7-flash',
      'google/gemini-3.6-flash',
      'google/gemini-3.5-flash',
      'google/gemini-3.5-flash-lite',
      'google/gemini-3.1-flash-lite',
      'sakana/fugu-ultra',
      'meta/muse-spark-1.1',
      'meta/muse-spark-1.2',
      'meta/muse-spark-1.2-contributor',
      'meta/muse-spark-1.3',
      'meta/muse-spark-1.3-contributor',
      'xai/grok-4.5',
      'xai/grok-4.6',
      'xai/grok-4.7',
    ],
    // `cmdc --help` 의 --permission-mode 값 그대로(standard, plan, accept-edits, yolo).
    modes: ['standard', 'plan', 'accept-edits', 'yolo'],
    notes: 'models 는 `cmdc --list-models`, modes 는 `cmdc --help` 실측값(v1.73.2). 화면에서 편집한다.',
    install: ['npm i -g command-code@latest'],
    installRequire: 'npm',
    installPrerequisite: ['nvm install lts', 'nvm use lts'],
  },
  GEMINI: {
    models: [],
    modes: [],
    notes: 'CLI 설치 후 --help 로 확인해 채운다',
    install: ['npm install -g @google/gemini-cli'],
    installRequire: 'npm',
    installPrerequisite: ['nvm install lts', 'nvm use lts'],
  },
};

export const PROVIDER_KEY_LABELS = DEFAULT_PROVIDER_NAMES;
